---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volsync-dest-app-volume-restore
spec:
  accessModes:
    - ReadWriteOnce
  dataSource:
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
    name: <SNAPSHOTNAMEHERE>
  resources:
    requests:
      storage: 10Gi
